[package]
name = "AgentManager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
console = "0.15"
dialoguer = "0.11"
directories = "5.0"
serde = { version = "1.0", features = ["derive"] }
skim = "0.10"
toml = "0.8"
